### ISSUE TITLE
Implements sidebar icons

### ISSUE THREAD

**Issue by cellulosa** [kkga/spacegray#128]
The Build 3065 of Sublime Text 3 implements some new functionality, among which sidebar icons ([see here](http://www.sublimetext.com/3)). Such functionality does not seem to be supported at current state by spacegray.

**Comment by cellulosa** [comment]
Does any of you guys have an idea about why [these](https://github.com/mrmartineau/SetiUI-Icons-Sublime) do not work with Spacegray? I've created the file `Spacegrey Light.sublime-theme` under the folder `Library/Application Support/Sublime Text 3/Packages/User/Theme - Spacegrey` but no icons show up

**Comment by marcofugaro** [comment]
@cellulosa try this, they're already implemented in this beta release

https://github.com/kurtextrem/spacegray/releases/tag/1.3.0-beta.3

**Comment by cellulosa** [comment]
Great, thank you! I'd love to see them implemented into Spacegray Light.

**Comment by nfantone** [comment]
@kurtextrem @cellulosa I've tried the beta.3 version you mentioned. While it works, my find bar (and any other search input) now looks like this:

<img width="1254" alt="screen shot 2016-01-08 at 1 15 12 am" src="https://cloud.githubusercontent.com/assets/476069/12190265/59aa3f66-b5a5-11e5-9d50-5ec77935363e.png">


Any ideas?

**Comment by bjankord** [comment]
@nfantone Its a feature, not a bug. ;)

**Comment by marcofugaro** [comment]
@nfantone check out [my fork](https://github.com/marcofugaro/spacegray), I fixed it

**Comment by nfantone** [comment]
@bjankord It's still hard for me to figure out if your comment has some truth in it or not. I'll go ahead and asume it doesn't.

@marcofugaro So, you've forked the fork. This is getting forkier by the minute.

**Comment by nfantone** [comment]
@marcofugaro It works wonders, thank you very much. Have you considered a PR to the original repo?

**Comment by marcofugaro** [comment]
@nfantone I don't know if they want to implement the filicons in the main theme though, will definetly ask them now that you bring it up, but the icons still need more polishing, some are indistinguible with the darker spacegray theme (sass icon) and the mac-like folder icon is just plain ugly and doesn't fit with the theme feel to me, will maybe work on that when I can, help is very much appreciated!

**Comment by kurtextrem** [comment]
I'd definitely merge PRs to my repo (or add contributors if anyone is willing to do).

**Comment by nfantone** [comment]
@marcofugaro @kurtextrem Talking about enhancements, I've tweaked some settings and override some icons and managed to get the sidebar looking like this:

<img width="1280" alt="screen shot 2016-01-10 at 4 12 07 pm" src="https://cloud.githubusercontent.com/assets/476069/12223484/bb76cd5e-b7b7-11e5-8132-8483f38ee63d.png">

* Changes opened/closed folder icons.
* Changes default file icon and some others.
* Mustache icons now showing properly.

Doesn't look half bad.

**Comment by marcofugaro** [comment]
good job @nfantone ! 
Feel free to fix anything weird that you encouter! For the fileicons to be ultimated, to me some still need to be fixed on the darker theme (see package.json and sass icon) as they are hard to distinguish due to the low contrast: Maybe make it load a brigher icon if the theme is dark, without alterating much the color of the brand... wonder how SetUI and Sublime-Marteial-Theme fixed this problem.

Also do you mind sharing it as your fork or something? I want those dope folder icons as well :)

**Comment by nfantone** [comment]
@marcofugaro All icons I've shamelessly stolen from other ST3 themes. Here's a list:

- [Seti ST3](https://github.com/ctf0/Seti_ST3/tree/master/icons)
- [Cyanide](https://github.com/lefoy/cyanide-theme/tree/master/icons)
- [Cobalt](https://github.com/wesbos/cobalt2/tree/master/icons)
- [Predawn](https://github.com/jamiewilson/predawn/tree/master/icons)

And [here](http://cl.ly/311m1R3o120n) is a `.zip` I've found with some more custom icons from [a post in Reddit](https://www.reddit.com/r/SublimeText/comments/2fjchi/list_of_themes_with_sidebar_icons_3062/).

My folder icons are from some flavour of Cyanide (don't exactly remember which one).

I've also fixed the dark colouring and now icons display brighter. Just look for `"layer0.tint"` property under "Sidebar file icons" in `Spacegray.sublime-theme` and comment it out, like so:

```javascript
// Sidebar file icons
{
        "class": "icon_file_type",
        // layer0.texture is filled in by code with the relevant icon name
        "layer0.opacity": 0.8,
        //"layer0.tint": [89, 103, 115],
        "content_margin": [10, 10]
    },
```

**Comment by marcofugaro** [comment]
@nfantone thanks dude, I managed to put all together and fix the behaviour of the icons, [here it is!](https://github.com/marcofugaro/spacegray/tree/betterfileicons)

Still having the same problem you had, the icons of mustache, handlebars, ai, ps, coffeescript sass and swift files don't show up at all.. How did you fix it?

![Example](http://i.imgur.com/LEbovVF.png)

I believe it is a ST3 problem not recognizing the languages?

**Comment by prog-rajkamal** [comment]
@marcofugaro I am trying to install your fork on my machine. Windows 8 64 bit with ST 3 build 3114.But I am failing. can you update your fork's readme with correct instructions?

**Comment by borishere** [comment]
Hi dear @marcofugaro. Please tell how I can install spacegray theme with icons.

**Comment by marcofugaro** [comment]
done #185

**Comment by wojciechmorawski** [comment]
Funny thing :) I've just install your theme (which is absolutely great!!!) and add -  "spacegray_fileicons": true - to my config and nothing happened :) . So I've gone to Spacegray.sublime-theme find FIX ICON BUG BY REMOVING THEM section, and removed it. It work's like a charm now.

OS X 10.11.3, Sublime Text build 3126

**Comment by marcofugaro** [comment]
@wojciechmorawski that issue is fixed by default in the 1.3.0 version, working on updating it in the package control https://packagecontrol.io/packages/Theme - Spacegray

**Comment by nfantone** [comment]
Incidentally, you should consider supporting https://github.com/ihodev/sublime-file-icons

**Comment by marcofugaro** [comment]
@nfantone what do you mean supporting? I've tried that package before and it updates all the icons just fine.

**Comment by nfantone** [comment]
I meant [this](https://github.com/ihodev/sublime-file-icons#bring-support-to-your-theme). 

But you don't need to _actually_ do anything for those icons to work. I believe it overrides some of the themes settings to make it happen.

**Comment by marcofugaro** [comment]
Yeah it's nice how it extends the supported icons, but the icons they have don't fit with the spacegray theme, they fit the Material Theme.
Is there a way we can keep our icons using that plugin?
